
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  User: 'User',
  AdminWhitelist: 'AdminWhitelist',
  Category: 'Category',
  Product: 'Product',
  ProductTranslation: 'ProductTranslation',
  ProductImage: 'ProductImage',
  ProductOption: 'ProductOption',
  ProductOptionTranslation: 'ProductOptionTranslation',
  Purchase: 'Purchase',
  PurchaseItem: 'PurchaseItem'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  passwordHash: 'passwordHash',
  firstName: 'firstName',
  lastName: 'lastName',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  company: 'company',
  position: 'position'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const AdminWhitelistScalarFieldEnum = {
  id: 'id',
  ip: 'ip',
  note: 'note',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AdminWhitelistScalarFieldEnum = (typeof AdminWhitelistScalarFieldEnum)[keyof typeof AdminWhitelistScalarFieldEnum]


export const CategoryScalarFieldEnum = {
  id: 'id',
  title: 'title',
  deletedAt: 'deletedAt'
} as const

export type CategoryScalarFieldEnum = (typeof CategoryScalarFieldEnum)[keyof typeof CategoryScalarFieldEnum]


export const ProductScalarFieldEnum = {
  id: 'id',
  title: 'title',
  price: 'price',
  categoryId: 'categoryId',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProductScalarFieldEnum = (typeof ProductScalarFieldEnum)[keyof typeof ProductScalarFieldEnum]


export const ProductTranslationScalarFieldEnum = {
  productId: 'productId',
  localeCode: 'localeCode',
  title: 'title',
  price: 'price',
  description: 'description'
} as const

export type ProductTranslationScalarFieldEnum = (typeof ProductTranslationScalarFieldEnum)[keyof typeof ProductTranslationScalarFieldEnum]


export const ProductImageScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  url: 'url',
  localeCode: 'localeCode',
  createdAt: 'createdAt'
} as const

export type ProductImageScalarFieldEnum = (typeof ProductImageScalarFieldEnum)[keyof typeof ProductImageScalarFieldEnum]


export const ProductOptionScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  type: 'type',
  isRequired: 'isRequired',
  isRecurring: 'isRecurring',
  priceAmount: 'priceAmount',
  currency: 'currency',
  billingPeriod: 'billingPeriod',
  sortOrder: 'sortOrder',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProductOptionScalarFieldEnum = (typeof ProductOptionScalarFieldEnum)[keyof typeof ProductOptionScalarFieldEnum]


export const ProductOptionTranslationScalarFieldEnum = {
  productOptionId: 'productOptionId',
  localeCode: 'localeCode',
  title: 'title',
  description: 'description',
  priceLabel: 'priceLabel'
} as const

export type ProductOptionTranslationScalarFieldEnum = (typeof ProductOptionTranslationScalarFieldEnum)[keyof typeof ProductOptionTranslationScalarFieldEnum]


export const PurchaseScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  orderNumber: 'orderNumber',
  status: 'status',
  totalAmount: 'totalAmount',
  currency: 'currency',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PurchaseScalarFieldEnum = (typeof PurchaseScalarFieldEnum)[keyof typeof PurchaseScalarFieldEnum]


export const PurchaseItemScalarFieldEnum = {
  id: 'id',
  purchaseId: 'purchaseId',
  productId: 'productId',
  title: 'title',
  quantity: 'quantity',
  unitPrice: 'unitPrice',
  currency: 'currency',
  createdAt: 'createdAt'
} as const

export type PurchaseItemScalarFieldEnum = (typeof PurchaseItemScalarFieldEnum)[keyof typeof PurchaseItemScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const UserOrderByRelevanceFieldEnum = {
  id: 'id',
  email: 'email',
  passwordHash: 'passwordHash',
  firstName: 'firstName',
  lastName: 'lastName',
  company: 'company',
  position: 'position'
} as const

export type UserOrderByRelevanceFieldEnum = (typeof UserOrderByRelevanceFieldEnum)[keyof typeof UserOrderByRelevanceFieldEnum]


export const AdminWhitelistOrderByRelevanceFieldEnum = {
  ip: 'ip',
  note: 'note'
} as const

export type AdminWhitelistOrderByRelevanceFieldEnum = (typeof AdminWhitelistOrderByRelevanceFieldEnum)[keyof typeof AdminWhitelistOrderByRelevanceFieldEnum]


export const CategoryOrderByRelevanceFieldEnum = {
  id: 'id',
  title: 'title'
} as const

export type CategoryOrderByRelevanceFieldEnum = (typeof CategoryOrderByRelevanceFieldEnum)[keyof typeof CategoryOrderByRelevanceFieldEnum]


export const ProductOrderByRelevanceFieldEnum = {
  id: 'id',
  title: 'title',
  price: 'price',
  categoryId: 'categoryId'
} as const

export type ProductOrderByRelevanceFieldEnum = (typeof ProductOrderByRelevanceFieldEnum)[keyof typeof ProductOrderByRelevanceFieldEnum]


export const ProductTranslationOrderByRelevanceFieldEnum = {
  productId: 'productId',
  localeCode: 'localeCode',
  title: 'title',
  price: 'price',
  description: 'description'
} as const

export type ProductTranslationOrderByRelevanceFieldEnum = (typeof ProductTranslationOrderByRelevanceFieldEnum)[keyof typeof ProductTranslationOrderByRelevanceFieldEnum]


export const ProductImageOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  url: 'url',
  localeCode: 'localeCode'
} as const

export type ProductImageOrderByRelevanceFieldEnum = (typeof ProductImageOrderByRelevanceFieldEnum)[keyof typeof ProductImageOrderByRelevanceFieldEnum]


export const ProductOptionOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  type: 'type',
  currency: 'currency',
  billingPeriod: 'billingPeriod'
} as const

export type ProductOptionOrderByRelevanceFieldEnum = (typeof ProductOptionOrderByRelevanceFieldEnum)[keyof typeof ProductOptionOrderByRelevanceFieldEnum]


export const ProductOptionTranslationOrderByRelevanceFieldEnum = {
  productOptionId: 'productOptionId',
  localeCode: 'localeCode',
  title: 'title',
  description: 'description',
  priceLabel: 'priceLabel'
} as const

export type ProductOptionTranslationOrderByRelevanceFieldEnum = (typeof ProductOptionTranslationOrderByRelevanceFieldEnum)[keyof typeof ProductOptionTranslationOrderByRelevanceFieldEnum]


export const PurchaseOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  orderNumber: 'orderNumber',
  status: 'status',
  currency: 'currency',
  notes: 'notes'
} as const

export type PurchaseOrderByRelevanceFieldEnum = (typeof PurchaseOrderByRelevanceFieldEnum)[keyof typeof PurchaseOrderByRelevanceFieldEnum]


export const PurchaseItemOrderByRelevanceFieldEnum = {
  id: 'id',
  purchaseId: 'purchaseId',
  productId: 'productId',
  title: 'title',
  currency: 'currency'
} as const

export type PurchaseItemOrderByRelevanceFieldEnum = (typeof PurchaseItemOrderByRelevanceFieldEnum)[keyof typeof PurchaseItemOrderByRelevanceFieldEnum]

