
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model User
 * *
 *  * ========= USERS =========
 */
export type User = Prisma.UserModel
/**
 * Model AdminWhitelist
 * 
 */
export type AdminWhitelist = Prisma.AdminWhitelistModel
/**
 * Model Category
 * *
 *  * ========= CATEGORIES =========
 */
export type Category = Prisma.CategoryModel
/**
 * Model Product
 * *
 *  * ========= PRODUCTS =========
 */
export type Product = Prisma.ProductModel
/**
 * Model ProductTranslation
 * 
 */
export type ProductTranslation = Prisma.ProductTranslationModel
/**
 * Model ProductImage
 * 
 */
export type ProductImage = Prisma.ProductImageModel
/**
 * Model ProductOption
 * *
 *  * ========= PRODUCT OPTIONS =========
 */
export type ProductOption = Prisma.ProductOptionModel
/**
 * Model ProductOptionTranslation
 * 
 */
export type ProductOptionTranslation = Prisma.ProductOptionTranslationModel
/**
 * Model Purchase
 * *
 *  * ========= PURCHASES =========
 */
export type Purchase = Prisma.PurchaseModel
/**
 * Model PurchaseItem
 * 
 */
export type PurchaseItem = Prisma.PurchaseItemModel
