
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `ProductOptionTranslation` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model ProductOptionTranslation
 * 
 */
export type ProductOptionTranslationModel = runtime.Types.Result.DefaultSelection<Prisma.$ProductOptionTranslationPayload>

export type AggregateProductOptionTranslation = {
  _count: ProductOptionTranslationCountAggregateOutputType | null
  _min: ProductOptionTranslationMinAggregateOutputType | null
  _max: ProductOptionTranslationMaxAggregateOutputType | null
}

export type ProductOptionTranslationMinAggregateOutputType = {
  productOptionId: string | null
  localeCode: string | null
  title: string | null
  description: string | null
  priceLabel: string | null
}

export type ProductOptionTranslationMaxAggregateOutputType = {
  productOptionId: string | null
  localeCode: string | null
  title: string | null
  description: string | null
  priceLabel: string | null
}

export type ProductOptionTranslationCountAggregateOutputType = {
  productOptionId: number
  localeCode: number
  title: number
  description: number
  priceLabel: number
  _all: number
}


export type ProductOptionTranslationMinAggregateInputType = {
  productOptionId?: true
  localeCode?: true
  title?: true
  description?: true
  priceLabel?: true
}

export type ProductOptionTranslationMaxAggregateInputType = {
  productOptionId?: true
  localeCode?: true
  title?: true
  description?: true
  priceLabel?: true
}

export type ProductOptionTranslationCountAggregateInputType = {
  productOptionId?: true
  localeCode?: true
  title?: true
  description?: true
  priceLabel?: true
  _all?: true
}

export type ProductOptionTranslationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProductOptionTranslation to aggregate.
   */
  where?: Prisma.ProductOptionTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductOptionTranslations to fetch.
   */
  orderBy?: Prisma.ProductOptionTranslationOrderByWithRelationInput | Prisma.ProductOptionTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProductOptionTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductOptionTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductOptionTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProductOptionTranslations
  **/
  _count?: true | ProductOptionTranslationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProductOptionTranslationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProductOptionTranslationMaxAggregateInputType
}

export type GetProductOptionTranslationAggregateType<T extends ProductOptionTranslationAggregateArgs> = {
      [P in keyof T & keyof AggregateProductOptionTranslation]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProductOptionTranslation[P]>
    : Prisma.GetScalarType<T[P], AggregateProductOptionTranslation[P]>
}




export type ProductOptionTranslationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductOptionTranslationWhereInput
  orderBy?: Prisma.ProductOptionTranslationOrderByWithAggregationInput | Prisma.ProductOptionTranslationOrderByWithAggregationInput[]
  by: Prisma.ProductOptionTranslationScalarFieldEnum[] | Prisma.ProductOptionTranslationScalarFieldEnum
  having?: Prisma.ProductOptionTranslationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProductOptionTranslationCountAggregateInputType | true
  _min?: ProductOptionTranslationMinAggregateInputType
  _max?: ProductOptionTranslationMaxAggregateInputType
}

export type ProductOptionTranslationGroupByOutputType = {
  productOptionId: string
  localeCode: string
  title: string
  description: string | null
  priceLabel: string | null
  _count: ProductOptionTranslationCountAggregateOutputType | null
  _min: ProductOptionTranslationMinAggregateOutputType | null
  _max: ProductOptionTranslationMaxAggregateOutputType | null
}

type GetProductOptionTranslationGroupByPayload<T extends ProductOptionTranslationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProductOptionTranslationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProductOptionTranslationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProductOptionTranslationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProductOptionTranslationGroupByOutputType[P]>
      }
    >
  >



export type ProductOptionTranslationWhereInput = {
  AND?: Prisma.ProductOptionTranslationWhereInput | Prisma.ProductOptionTranslationWhereInput[]
  OR?: Prisma.ProductOptionTranslationWhereInput[]
  NOT?: Prisma.ProductOptionTranslationWhereInput | Prisma.ProductOptionTranslationWhereInput[]
  productOptionId?: Prisma.StringFilter<"ProductOptionTranslation"> | string
  localeCode?: Prisma.StringFilter<"ProductOptionTranslation"> | string
  title?: Prisma.StringFilter<"ProductOptionTranslation"> | string
  description?: Prisma.StringNullableFilter<"ProductOptionTranslation"> | string | null
  priceLabel?: Prisma.StringNullableFilter<"ProductOptionTranslation"> | string | null
  option?: Prisma.XOR<Prisma.ProductOptionScalarRelationFilter, Prisma.ProductOptionWhereInput>
}

export type ProductOptionTranslationOrderByWithRelationInput = {
  productOptionId?: Prisma.SortOrder
  localeCode?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  priceLabel?: Prisma.SortOrderInput | Prisma.SortOrder
  option?: Prisma.ProductOptionOrderByWithRelationInput
  _relevance?: Prisma.ProductOptionTranslationOrderByRelevanceInput
}

export type ProductOptionTranslationWhereUniqueInput = Prisma.AtLeast<{
  productOptionId_localeCode?: Prisma.ProductOptionTranslationProductOptionIdLocaleCodeCompoundUniqueInput
  AND?: Prisma.ProductOptionTranslationWhereInput | Prisma.ProductOptionTranslationWhereInput[]
  OR?: Prisma.ProductOptionTranslationWhereInput[]
  NOT?: Prisma.ProductOptionTranslationWhereInput | Prisma.ProductOptionTranslationWhereInput[]
  productOptionId?: Prisma.StringFilter<"ProductOptionTranslation"> | string
  localeCode?: Prisma.StringFilter<"ProductOptionTranslation"> | string
  title?: Prisma.StringFilter<"ProductOptionTranslation"> | string
  description?: Prisma.StringNullableFilter<"ProductOptionTranslation"> | string | null
  priceLabel?: Prisma.StringNullableFilter<"ProductOptionTranslation"> | string | null
  option?: Prisma.XOR<Prisma.ProductOptionScalarRelationFilter, Prisma.ProductOptionWhereInput>
}, "productOptionId_localeCode">

export type ProductOptionTranslationOrderByWithAggregationInput = {
  productOptionId?: Prisma.SortOrder
  localeCode?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  priceLabel?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ProductOptionTranslationCountOrderByAggregateInput
  _max?: Prisma.ProductOptionTranslationMaxOrderByAggregateInput
  _min?: Prisma.ProductOptionTranslationMinOrderByAggregateInput
}

export type ProductOptionTranslationScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProductOptionTranslationScalarWhereWithAggregatesInput | Prisma.ProductOptionTranslationScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProductOptionTranslationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProductOptionTranslationScalarWhereWithAggregatesInput | Prisma.ProductOptionTranslationScalarWhereWithAggregatesInput[]
  productOptionId?: Prisma.StringWithAggregatesFilter<"ProductOptionTranslation"> | string
  localeCode?: Prisma.StringWithAggregatesFilter<"ProductOptionTranslation"> | string
  title?: Prisma.StringWithAggregatesFilter<"ProductOptionTranslation"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"ProductOptionTranslation"> | string | null
  priceLabel?: Prisma.StringNullableWithAggregatesFilter<"ProductOptionTranslation"> | string | null
}

export type ProductOptionTranslationCreateInput = {
  localeCode: string
  title: string
  description?: string | null
  priceLabel?: string | null
  option: Prisma.ProductOptionCreateNestedOneWithoutTranslationsInput
}

export type ProductOptionTranslationUncheckedCreateInput = {
  productOptionId: string
  localeCode: string
  title: string
  description?: string | null
  priceLabel?: string | null
}

export type ProductOptionTranslationUpdateInput = {
  localeCode?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priceLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  option?: Prisma.ProductOptionUpdateOneRequiredWithoutTranslationsNestedInput
}

export type ProductOptionTranslationUncheckedUpdateInput = {
  productOptionId?: Prisma.StringFieldUpdateOperationsInput | string
  localeCode?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priceLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProductOptionTranslationCreateManyInput = {
  productOptionId: string
  localeCode: string
  title: string
  description?: string | null
  priceLabel?: string | null
}

export type ProductOptionTranslationUpdateManyMutationInput = {
  localeCode?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priceLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProductOptionTranslationUncheckedUpdateManyInput = {
  productOptionId?: Prisma.StringFieldUpdateOperationsInput | string
  localeCode?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priceLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProductOptionTranslationListRelationFilter = {
  every?: Prisma.ProductOptionTranslationWhereInput
  some?: Prisma.ProductOptionTranslationWhereInput
  none?: Prisma.ProductOptionTranslationWhereInput
}

export type ProductOptionTranslationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProductOptionTranslationOrderByRelevanceInput = {
  fields: Prisma.ProductOptionTranslationOrderByRelevanceFieldEnum | Prisma.ProductOptionTranslationOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ProductOptionTranslationProductOptionIdLocaleCodeCompoundUniqueInput = {
  productOptionId: string
  localeCode: string
}

export type ProductOptionTranslationCountOrderByAggregateInput = {
  productOptionId?: Prisma.SortOrder
  localeCode?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  priceLabel?: Prisma.SortOrder
}

export type ProductOptionTranslationMaxOrderByAggregateInput = {
  productOptionId?: Prisma.SortOrder
  localeCode?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  priceLabel?: Prisma.SortOrder
}

export type ProductOptionTranslationMinOrderByAggregateInput = {
  productOptionId?: Prisma.SortOrder
  localeCode?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  priceLabel?: Prisma.SortOrder
}

export type ProductOptionTranslationCreateNestedManyWithoutOptionInput = {
  create?: Prisma.XOR<Prisma.ProductOptionTranslationCreateWithoutOptionInput, Prisma.ProductOptionTranslationUncheckedCreateWithoutOptionInput> | Prisma.ProductOptionTranslationCreateWithoutOptionInput[] | Prisma.ProductOptionTranslationUncheckedCreateWithoutOptionInput[]
  connectOrCreate?: Prisma.ProductOptionTranslationCreateOrConnectWithoutOptionInput | Prisma.ProductOptionTranslationCreateOrConnectWithoutOptionInput[]
  createMany?: Prisma.ProductOptionTranslationCreateManyOptionInputEnvelope
  connect?: Prisma.ProductOptionTranslationWhereUniqueInput | Prisma.ProductOptionTranslationWhereUniqueInput[]
}

export type ProductOptionTranslationUncheckedCreateNestedManyWithoutOptionInput = {
  create?: Prisma.XOR<Prisma.ProductOptionTranslationCreateWithoutOptionInput, Prisma.ProductOptionTranslationUncheckedCreateWithoutOptionInput> | Prisma.ProductOptionTranslationCreateWithoutOptionInput[] | Prisma.ProductOptionTranslationUncheckedCreateWithoutOptionInput[]
  connectOrCreate?: Prisma.ProductOptionTranslationCreateOrConnectWithoutOptionInput | Prisma.ProductOptionTranslationCreateOrConnectWithoutOptionInput[]
  createMany?: Prisma.ProductOptionTranslationCreateManyOptionInputEnvelope
  connect?: Prisma.ProductOptionTranslationWhereUniqueInput | Prisma.ProductOptionTranslationWhereUniqueInput[]
}

export type ProductOptionTranslationUpdateManyWithoutOptionNestedInput = {
  create?: Prisma.XOR<Prisma.ProductOptionTranslationCreateWithoutOptionInput, Prisma.ProductOptionTranslationUncheckedCreateWithoutOptionInput> | Prisma.ProductOptionTranslationCreateWithoutOptionInput[] | Prisma.ProductOptionTranslationUncheckedCreateWithoutOptionInput[]
  connectOrCreate?: Prisma.ProductOptionTranslationCreateOrConnectWithoutOptionInput | Prisma.ProductOptionTranslationCreateOrConnectWithoutOptionInput[]
  upsert?: Prisma.ProductOptionTranslationUpsertWithWhereUniqueWithoutOptionInput | Prisma.ProductOptionTranslationUpsertWithWhereUniqueWithoutOptionInput[]
  createMany?: Prisma.ProductOptionTranslationCreateManyOptionInputEnvelope
  set?: Prisma.ProductOptionTranslationWhereUniqueInput | Prisma.ProductOptionTranslationWhereUniqueInput[]
  disconnect?: Prisma.ProductOptionTranslationWhereUniqueInput | Prisma.ProductOptionTranslationWhereUniqueInput[]
  delete?: Prisma.ProductOptionTranslationWhereUniqueInput | Prisma.ProductOptionTranslationWhereUniqueInput[]
  connect?: Prisma.ProductOptionTranslationWhereUniqueInput | Prisma.ProductOptionTranslationWhereUniqueInput[]
  update?: Prisma.ProductOptionTranslationUpdateWithWhereUniqueWithoutOptionInput | Prisma.ProductOptionTranslationUpdateWithWhereUniqueWithoutOptionInput[]
  updateMany?: Prisma.ProductOptionTranslationUpdateManyWithWhereWithoutOptionInput | Prisma.ProductOptionTranslationUpdateManyWithWhereWithoutOptionInput[]
  deleteMany?: Prisma.ProductOptionTranslationScalarWhereInput | Prisma.ProductOptionTranslationScalarWhereInput[]
}

export type ProductOptionTranslationUncheckedUpdateManyWithoutOptionNestedInput = {
  create?: Prisma.XOR<Prisma.ProductOptionTranslationCreateWithoutOptionInput, Prisma.ProductOptionTranslationUncheckedCreateWithoutOptionInput> | Prisma.ProductOptionTranslationCreateWithoutOptionInput[] | Prisma.ProductOptionTranslationUncheckedCreateWithoutOptionInput[]
  connectOrCreate?: Prisma.ProductOptionTranslationCreateOrConnectWithoutOptionInput | Prisma.ProductOptionTranslationCreateOrConnectWithoutOptionInput[]
  upsert?: Prisma.ProductOptionTranslationUpsertWithWhereUniqueWithoutOptionInput | Prisma.ProductOptionTranslationUpsertWithWhereUniqueWithoutOptionInput[]
  createMany?: Prisma.ProductOptionTranslationCreateManyOptionInputEnvelope
  set?: Prisma.ProductOptionTranslationWhereUniqueInput | Prisma.ProductOptionTranslationWhereUniqueInput[]
  disconnect?: Prisma.ProductOptionTranslationWhereUniqueInput | Prisma.ProductOptionTranslationWhereUniqueInput[]
  delete?: Prisma.ProductOptionTranslationWhereUniqueInput | Prisma.ProductOptionTranslationWhereUniqueInput[]
  connect?: Prisma.ProductOptionTranslationWhereUniqueInput | Prisma.ProductOptionTranslationWhereUniqueInput[]
  update?: Prisma.ProductOptionTranslationUpdateWithWhereUniqueWithoutOptionInput | Prisma.ProductOptionTranslationUpdateWithWhereUniqueWithoutOptionInput[]
  updateMany?: Prisma.ProductOptionTranslationUpdateManyWithWhereWithoutOptionInput | Prisma.ProductOptionTranslationUpdateManyWithWhereWithoutOptionInput[]
  deleteMany?: Prisma.ProductOptionTranslationScalarWhereInput | Prisma.ProductOptionTranslationScalarWhereInput[]
}

export type ProductOptionTranslationCreateWithoutOptionInput = {
  localeCode: string
  title: string
  description?: string | null
  priceLabel?: string | null
}

export type ProductOptionTranslationUncheckedCreateWithoutOptionInput = {
  localeCode: string
  title: string
  description?: string | null
  priceLabel?: string | null
}

export type ProductOptionTranslationCreateOrConnectWithoutOptionInput = {
  where: Prisma.ProductOptionTranslationWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductOptionTranslationCreateWithoutOptionInput, Prisma.ProductOptionTranslationUncheckedCreateWithoutOptionInput>
}

export type ProductOptionTranslationCreateManyOptionInputEnvelope = {
  data: Prisma.ProductOptionTranslationCreateManyOptionInput | Prisma.ProductOptionTranslationCreateManyOptionInput[]
  skipDuplicates?: boolean
}

export type ProductOptionTranslationUpsertWithWhereUniqueWithoutOptionInput = {
  where: Prisma.ProductOptionTranslationWhereUniqueInput
  update: Prisma.XOR<Prisma.ProductOptionTranslationUpdateWithoutOptionInput, Prisma.ProductOptionTranslationUncheckedUpdateWithoutOptionInput>
  create: Prisma.XOR<Prisma.ProductOptionTranslationCreateWithoutOptionInput, Prisma.ProductOptionTranslationUncheckedCreateWithoutOptionInput>
}

export type ProductOptionTranslationUpdateWithWhereUniqueWithoutOptionInput = {
  where: Prisma.ProductOptionTranslationWhereUniqueInput
  data: Prisma.XOR<Prisma.ProductOptionTranslationUpdateWithoutOptionInput, Prisma.ProductOptionTranslationUncheckedUpdateWithoutOptionInput>
}

export type ProductOptionTranslationUpdateManyWithWhereWithoutOptionInput = {
  where: Prisma.ProductOptionTranslationScalarWhereInput
  data: Prisma.XOR<Prisma.ProductOptionTranslationUpdateManyMutationInput, Prisma.ProductOptionTranslationUncheckedUpdateManyWithoutOptionInput>
}

export type ProductOptionTranslationScalarWhereInput = {
  AND?: Prisma.ProductOptionTranslationScalarWhereInput | Prisma.ProductOptionTranslationScalarWhereInput[]
  OR?: Prisma.ProductOptionTranslationScalarWhereInput[]
  NOT?: Prisma.ProductOptionTranslationScalarWhereInput | Prisma.ProductOptionTranslationScalarWhereInput[]
  productOptionId?: Prisma.StringFilter<"ProductOptionTranslation"> | string
  localeCode?: Prisma.StringFilter<"ProductOptionTranslation"> | string
  title?: Prisma.StringFilter<"ProductOptionTranslation"> | string
  description?: Prisma.StringNullableFilter<"ProductOptionTranslation"> | string | null
  priceLabel?: Prisma.StringNullableFilter<"ProductOptionTranslation"> | string | null
}

export type ProductOptionTranslationCreateManyOptionInput = {
  localeCode: string
  title: string
  description?: string | null
  priceLabel?: string | null
}

export type ProductOptionTranslationUpdateWithoutOptionInput = {
  localeCode?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priceLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProductOptionTranslationUncheckedUpdateWithoutOptionInput = {
  localeCode?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priceLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProductOptionTranslationUncheckedUpdateManyWithoutOptionInput = {
  localeCode?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priceLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type ProductOptionTranslationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  productOptionId?: boolean
  localeCode?: boolean
  title?: boolean
  description?: boolean
  priceLabel?: boolean
  option?: boolean | Prisma.ProductOptionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productOptionTranslation"]>



export type ProductOptionTranslationSelectScalar = {
  productOptionId?: boolean
  localeCode?: boolean
  title?: boolean
  description?: boolean
  priceLabel?: boolean
}

export type ProductOptionTranslationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"productOptionId" | "localeCode" | "title" | "description" | "priceLabel", ExtArgs["result"]["productOptionTranslation"]>
export type ProductOptionTranslationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  option?: boolean | Prisma.ProductOptionDefaultArgs<ExtArgs>
}

export type $ProductOptionTranslationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProductOptionTranslation"
  objects: {
    option: Prisma.$ProductOptionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    productOptionId: string
    localeCode: string
    title: string
    description: string | null
    priceLabel: string | null
  }, ExtArgs["result"]["productOptionTranslation"]>
  composites: {}
}

export type ProductOptionTranslationGetPayload<S extends boolean | null | undefined | ProductOptionTranslationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProductOptionTranslationPayload, S>

export type ProductOptionTranslationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProductOptionTranslationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProductOptionTranslationCountAggregateInputType | true
  }

export interface ProductOptionTranslationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProductOptionTranslation'], meta: { name: 'ProductOptionTranslation' } }
  /**
   * Find zero or one ProductOptionTranslation that matches the filter.
   * @param {ProductOptionTranslationFindUniqueArgs} args - Arguments to find a ProductOptionTranslation
   * @example
   * // Get one ProductOptionTranslation
   * const productOptionTranslation = await prisma.productOptionTranslation.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProductOptionTranslationFindUniqueArgs>(args: Prisma.SelectSubset<T, ProductOptionTranslationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProductOptionTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProductOptionTranslationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProductOptionTranslation that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProductOptionTranslationFindUniqueOrThrowArgs} args - Arguments to find a ProductOptionTranslation
   * @example
   * // Get one ProductOptionTranslation
   * const productOptionTranslation = await prisma.productOptionTranslation.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProductOptionTranslationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProductOptionTranslationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductOptionTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProductOptionTranslationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProductOptionTranslation that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductOptionTranslationFindFirstArgs} args - Arguments to find a ProductOptionTranslation
   * @example
   * // Get one ProductOptionTranslation
   * const productOptionTranslation = await prisma.productOptionTranslation.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProductOptionTranslationFindFirstArgs>(args?: Prisma.SelectSubset<T, ProductOptionTranslationFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProductOptionTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProductOptionTranslationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProductOptionTranslation that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductOptionTranslationFindFirstOrThrowArgs} args - Arguments to find a ProductOptionTranslation
   * @example
   * // Get one ProductOptionTranslation
   * const productOptionTranslation = await prisma.productOptionTranslation.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProductOptionTranslationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProductOptionTranslationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductOptionTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProductOptionTranslationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProductOptionTranslations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductOptionTranslationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProductOptionTranslations
   * const productOptionTranslations = await prisma.productOptionTranslation.findMany()
   * 
   * // Get first 10 ProductOptionTranslations
   * const productOptionTranslations = await prisma.productOptionTranslation.findMany({ take: 10 })
   * 
   * // Only select the `productOptionId`
   * const productOptionTranslationWithProductOptionIdOnly = await prisma.productOptionTranslation.findMany({ select: { productOptionId: true } })
   * 
   */
  findMany<T extends ProductOptionTranslationFindManyArgs>(args?: Prisma.SelectSubset<T, ProductOptionTranslationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductOptionTranslationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProductOptionTranslation.
   * @param {ProductOptionTranslationCreateArgs} args - Arguments to create a ProductOptionTranslation.
   * @example
   * // Create one ProductOptionTranslation
   * const ProductOptionTranslation = await prisma.productOptionTranslation.create({
   *   data: {
   *     // ... data to create a ProductOptionTranslation
   *   }
   * })
   * 
   */
  create<T extends ProductOptionTranslationCreateArgs>(args: Prisma.SelectSubset<T, ProductOptionTranslationCreateArgs<ExtArgs>>): Prisma.Prisma__ProductOptionTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProductOptionTranslationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProductOptionTranslations.
   * @param {ProductOptionTranslationCreateManyArgs} args - Arguments to create many ProductOptionTranslations.
   * @example
   * // Create many ProductOptionTranslations
   * const productOptionTranslation = await prisma.productOptionTranslation.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProductOptionTranslationCreateManyArgs>(args?: Prisma.SelectSubset<T, ProductOptionTranslationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a ProductOptionTranslation.
   * @param {ProductOptionTranslationDeleteArgs} args - Arguments to delete one ProductOptionTranslation.
   * @example
   * // Delete one ProductOptionTranslation
   * const ProductOptionTranslation = await prisma.productOptionTranslation.delete({
   *   where: {
   *     // ... filter to delete one ProductOptionTranslation
   *   }
   * })
   * 
   */
  delete<T extends ProductOptionTranslationDeleteArgs>(args: Prisma.SelectSubset<T, ProductOptionTranslationDeleteArgs<ExtArgs>>): Prisma.Prisma__ProductOptionTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProductOptionTranslationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProductOptionTranslation.
   * @param {ProductOptionTranslationUpdateArgs} args - Arguments to update one ProductOptionTranslation.
   * @example
   * // Update one ProductOptionTranslation
   * const productOptionTranslation = await prisma.productOptionTranslation.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProductOptionTranslationUpdateArgs>(args: Prisma.SelectSubset<T, ProductOptionTranslationUpdateArgs<ExtArgs>>): Prisma.Prisma__ProductOptionTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProductOptionTranslationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProductOptionTranslations.
   * @param {ProductOptionTranslationDeleteManyArgs} args - Arguments to filter ProductOptionTranslations to delete.
   * @example
   * // Delete a few ProductOptionTranslations
   * const { count } = await prisma.productOptionTranslation.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProductOptionTranslationDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProductOptionTranslationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProductOptionTranslations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductOptionTranslationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProductOptionTranslations
   * const productOptionTranslation = await prisma.productOptionTranslation.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProductOptionTranslationUpdateManyArgs>(args: Prisma.SelectSubset<T, ProductOptionTranslationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one ProductOptionTranslation.
   * @param {ProductOptionTranslationUpsertArgs} args - Arguments to update or create a ProductOptionTranslation.
   * @example
   * // Update or create a ProductOptionTranslation
   * const productOptionTranslation = await prisma.productOptionTranslation.upsert({
   *   create: {
   *     // ... data to create a ProductOptionTranslation
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProductOptionTranslation we want to update
   *   }
   * })
   */
  upsert<T extends ProductOptionTranslationUpsertArgs>(args: Prisma.SelectSubset<T, ProductOptionTranslationUpsertArgs<ExtArgs>>): Prisma.Prisma__ProductOptionTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProductOptionTranslationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProductOptionTranslations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductOptionTranslationCountArgs} args - Arguments to filter ProductOptionTranslations to count.
   * @example
   * // Count the number of ProductOptionTranslations
   * const count = await prisma.productOptionTranslation.count({
   *   where: {
   *     // ... the filter for the ProductOptionTranslations we want to count
   *   }
   * })
  **/
  count<T extends ProductOptionTranslationCountArgs>(
    args?: Prisma.Subset<T, ProductOptionTranslationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProductOptionTranslationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProductOptionTranslation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductOptionTranslationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProductOptionTranslationAggregateArgs>(args: Prisma.Subset<T, ProductOptionTranslationAggregateArgs>): Prisma.PrismaPromise<GetProductOptionTranslationAggregateType<T>>

  /**
   * Group by ProductOptionTranslation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductOptionTranslationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProductOptionTranslationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProductOptionTranslationGroupByArgs['orderBy'] }
      : { orderBy?: ProductOptionTranslationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProductOptionTranslationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProductOptionTranslationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProductOptionTranslation model
 */
readonly fields: ProductOptionTranslationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProductOptionTranslation.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProductOptionTranslationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  option<T extends Prisma.ProductOptionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductOptionDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductOptionClient<runtime.Types.Result.GetResult<Prisma.$ProductOptionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProductOptionTranslation model
 */
export interface ProductOptionTranslationFieldRefs {
  readonly productOptionId: Prisma.FieldRef<"ProductOptionTranslation", 'String'>
  readonly localeCode: Prisma.FieldRef<"ProductOptionTranslation", 'String'>
  readonly title: Prisma.FieldRef<"ProductOptionTranslation", 'String'>
  readonly description: Prisma.FieldRef<"ProductOptionTranslation", 'String'>
  readonly priceLabel: Prisma.FieldRef<"ProductOptionTranslation", 'String'>
}
    

// Custom InputTypes
/**
 * ProductOptionTranslation findUnique
 */
export type ProductOptionTranslationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductOptionTranslation
   */
  select?: Prisma.ProductOptionTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductOptionTranslation
   */
  omit?: Prisma.ProductOptionTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductOptionTranslationInclude<ExtArgs> | null
  /**
   * Filter, which ProductOptionTranslation to fetch.
   */
  where: Prisma.ProductOptionTranslationWhereUniqueInput
}

/**
 * ProductOptionTranslation findUniqueOrThrow
 */
export type ProductOptionTranslationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductOptionTranslation
   */
  select?: Prisma.ProductOptionTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductOptionTranslation
   */
  omit?: Prisma.ProductOptionTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductOptionTranslationInclude<ExtArgs> | null
  /**
   * Filter, which ProductOptionTranslation to fetch.
   */
  where: Prisma.ProductOptionTranslationWhereUniqueInput
}

/**
 * ProductOptionTranslation findFirst
 */
export type ProductOptionTranslationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductOptionTranslation
   */
  select?: Prisma.ProductOptionTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductOptionTranslation
   */
  omit?: Prisma.ProductOptionTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductOptionTranslationInclude<ExtArgs> | null
  /**
   * Filter, which ProductOptionTranslation to fetch.
   */
  where?: Prisma.ProductOptionTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductOptionTranslations to fetch.
   */
  orderBy?: Prisma.ProductOptionTranslationOrderByWithRelationInput | Prisma.ProductOptionTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProductOptionTranslations.
   */
  cursor?: Prisma.ProductOptionTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductOptionTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductOptionTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductOptionTranslations.
   */
  distinct?: Prisma.ProductOptionTranslationScalarFieldEnum | Prisma.ProductOptionTranslationScalarFieldEnum[]
}

/**
 * ProductOptionTranslation findFirstOrThrow
 */
export type ProductOptionTranslationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductOptionTranslation
   */
  select?: Prisma.ProductOptionTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductOptionTranslation
   */
  omit?: Prisma.ProductOptionTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductOptionTranslationInclude<ExtArgs> | null
  /**
   * Filter, which ProductOptionTranslation to fetch.
   */
  where?: Prisma.ProductOptionTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductOptionTranslations to fetch.
   */
  orderBy?: Prisma.ProductOptionTranslationOrderByWithRelationInput | Prisma.ProductOptionTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProductOptionTranslations.
   */
  cursor?: Prisma.ProductOptionTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductOptionTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductOptionTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductOptionTranslations.
   */
  distinct?: Prisma.ProductOptionTranslationScalarFieldEnum | Prisma.ProductOptionTranslationScalarFieldEnum[]
}

/**
 * ProductOptionTranslation findMany
 */
export type ProductOptionTranslationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductOptionTranslation
   */
  select?: Prisma.ProductOptionTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductOptionTranslation
   */
  omit?: Prisma.ProductOptionTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductOptionTranslationInclude<ExtArgs> | null
  /**
   * Filter, which ProductOptionTranslations to fetch.
   */
  where?: Prisma.ProductOptionTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductOptionTranslations to fetch.
   */
  orderBy?: Prisma.ProductOptionTranslationOrderByWithRelationInput | Prisma.ProductOptionTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProductOptionTranslations.
   */
  cursor?: Prisma.ProductOptionTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductOptionTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductOptionTranslations.
   */
  skip?: number
  distinct?: Prisma.ProductOptionTranslationScalarFieldEnum | Prisma.ProductOptionTranslationScalarFieldEnum[]
}

/**
 * ProductOptionTranslation create
 */
export type ProductOptionTranslationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductOptionTranslation
   */
  select?: Prisma.ProductOptionTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductOptionTranslation
   */
  omit?: Prisma.ProductOptionTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductOptionTranslationInclude<ExtArgs> | null
  /**
   * The data needed to create a ProductOptionTranslation.
   */
  data: Prisma.XOR<Prisma.ProductOptionTranslationCreateInput, Prisma.ProductOptionTranslationUncheckedCreateInput>
}

/**
 * ProductOptionTranslation createMany
 */
export type ProductOptionTranslationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProductOptionTranslations.
   */
  data: Prisma.ProductOptionTranslationCreateManyInput | Prisma.ProductOptionTranslationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ProductOptionTranslation update
 */
export type ProductOptionTranslationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductOptionTranslation
   */
  select?: Prisma.ProductOptionTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductOptionTranslation
   */
  omit?: Prisma.ProductOptionTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductOptionTranslationInclude<ExtArgs> | null
  /**
   * The data needed to update a ProductOptionTranslation.
   */
  data: Prisma.XOR<Prisma.ProductOptionTranslationUpdateInput, Prisma.ProductOptionTranslationUncheckedUpdateInput>
  /**
   * Choose, which ProductOptionTranslation to update.
   */
  where: Prisma.ProductOptionTranslationWhereUniqueInput
}

/**
 * ProductOptionTranslation updateMany
 */
export type ProductOptionTranslationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProductOptionTranslations.
   */
  data: Prisma.XOR<Prisma.ProductOptionTranslationUpdateManyMutationInput, Prisma.ProductOptionTranslationUncheckedUpdateManyInput>
  /**
   * Filter which ProductOptionTranslations to update
   */
  where?: Prisma.ProductOptionTranslationWhereInput
  /**
   * Limit how many ProductOptionTranslations to update.
   */
  limit?: number
}

/**
 * ProductOptionTranslation upsert
 */
export type ProductOptionTranslationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductOptionTranslation
   */
  select?: Prisma.ProductOptionTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductOptionTranslation
   */
  omit?: Prisma.ProductOptionTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductOptionTranslationInclude<ExtArgs> | null
  /**
   * The filter to search for the ProductOptionTranslation to update in case it exists.
   */
  where: Prisma.ProductOptionTranslationWhereUniqueInput
  /**
   * In case the ProductOptionTranslation found by the `where` argument doesn't exist, create a new ProductOptionTranslation with this data.
   */
  create: Prisma.XOR<Prisma.ProductOptionTranslationCreateInput, Prisma.ProductOptionTranslationUncheckedCreateInput>
  /**
   * In case the ProductOptionTranslation was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProductOptionTranslationUpdateInput, Prisma.ProductOptionTranslationUncheckedUpdateInput>
}

/**
 * ProductOptionTranslation delete
 */
export type ProductOptionTranslationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductOptionTranslation
   */
  select?: Prisma.ProductOptionTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductOptionTranslation
   */
  omit?: Prisma.ProductOptionTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductOptionTranslationInclude<ExtArgs> | null
  /**
   * Filter which ProductOptionTranslation to delete.
   */
  where: Prisma.ProductOptionTranslationWhereUniqueInput
}

/**
 * ProductOptionTranslation deleteMany
 */
export type ProductOptionTranslationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProductOptionTranslations to delete
   */
  where?: Prisma.ProductOptionTranslationWhereInput
  /**
   * Limit how many ProductOptionTranslations to delete.
   */
  limit?: number
}

/**
 * ProductOptionTranslation without action
 */
export type ProductOptionTranslationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductOptionTranslation
   */
  select?: Prisma.ProductOptionTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductOptionTranslation
   */
  omit?: Prisma.ProductOptionTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductOptionTranslationInclude<ExtArgs> | null
}
