
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `ProductTranslation` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model ProductTranslation
 * 
 */
export type ProductTranslationModel = runtime.Types.Result.DefaultSelection<Prisma.$ProductTranslationPayload>

export type AggregateProductTranslation = {
  _count: ProductTranslationCountAggregateOutputType | null
  _min: ProductTranslationMinAggregateOutputType | null
  _max: ProductTranslationMaxAggregateOutputType | null
}

export type ProductTranslationMinAggregateOutputType = {
  productId: string | null
  localeCode: string | null
  title: string | null
  price: string | null
  description: string | null
}

export type ProductTranslationMaxAggregateOutputType = {
  productId: string | null
  localeCode: string | null
  title: string | null
  price: string | null
  description: string | null
}

export type ProductTranslationCountAggregateOutputType = {
  productId: number
  localeCode: number
  title: number
  price: number
  description: number
  _all: number
}


export type ProductTranslationMinAggregateInputType = {
  productId?: true
  localeCode?: true
  title?: true
  price?: true
  description?: true
}

export type ProductTranslationMaxAggregateInputType = {
  productId?: true
  localeCode?: true
  title?: true
  price?: true
  description?: true
}

export type ProductTranslationCountAggregateInputType = {
  productId?: true
  localeCode?: true
  title?: true
  price?: true
  description?: true
  _all?: true
}

export type ProductTranslationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProductTranslation to aggregate.
   */
  where?: Prisma.ProductTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductTranslations to fetch.
   */
  orderBy?: Prisma.ProductTranslationOrderByWithRelationInput | Prisma.ProductTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProductTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProductTranslations
  **/
  _count?: true | ProductTranslationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProductTranslationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProductTranslationMaxAggregateInputType
}

export type GetProductTranslationAggregateType<T extends ProductTranslationAggregateArgs> = {
      [P in keyof T & keyof AggregateProductTranslation]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProductTranslation[P]>
    : Prisma.GetScalarType<T[P], AggregateProductTranslation[P]>
}




export type ProductTranslationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductTranslationWhereInput
  orderBy?: Prisma.ProductTranslationOrderByWithAggregationInput | Prisma.ProductTranslationOrderByWithAggregationInput[]
  by: Prisma.ProductTranslationScalarFieldEnum[] | Prisma.ProductTranslationScalarFieldEnum
  having?: Prisma.ProductTranslationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProductTranslationCountAggregateInputType | true
  _min?: ProductTranslationMinAggregateInputType
  _max?: ProductTranslationMaxAggregateInputType
}

export type ProductTranslationGroupByOutputType = {
  productId: string
  localeCode: string
  title: string
  price: string | null
  description: string | null
  _count: ProductTranslationCountAggregateOutputType | null
  _min: ProductTranslationMinAggregateOutputType | null
  _max: ProductTranslationMaxAggregateOutputType | null
}

type GetProductTranslationGroupByPayload<T extends ProductTranslationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProductTranslationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProductTranslationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProductTranslationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProductTranslationGroupByOutputType[P]>
      }
    >
  >



export type ProductTranslationWhereInput = {
  AND?: Prisma.ProductTranslationWhereInput | Prisma.ProductTranslationWhereInput[]
  OR?: Prisma.ProductTranslationWhereInput[]
  NOT?: Prisma.ProductTranslationWhereInput | Prisma.ProductTranslationWhereInput[]
  productId?: Prisma.StringFilter<"ProductTranslation"> | string
  localeCode?: Prisma.StringFilter<"ProductTranslation"> | string
  title?: Prisma.StringFilter<"ProductTranslation"> | string
  price?: Prisma.StringNullableFilter<"ProductTranslation"> | string | null
  description?: Prisma.StringNullableFilter<"ProductTranslation"> | string | null
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}

export type ProductTranslationOrderByWithRelationInput = {
  productId?: Prisma.SortOrder
  localeCode?: Prisma.SortOrder
  title?: Prisma.SortOrder
  price?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  product?: Prisma.ProductOrderByWithRelationInput
  _relevance?: Prisma.ProductTranslationOrderByRelevanceInput
}

export type ProductTranslationWhereUniqueInput = Prisma.AtLeast<{
  productId_localeCode?: Prisma.ProductTranslationProductIdLocaleCodeCompoundUniqueInput
  AND?: Prisma.ProductTranslationWhereInput | Prisma.ProductTranslationWhereInput[]
  OR?: Prisma.ProductTranslationWhereInput[]
  NOT?: Prisma.ProductTranslationWhereInput | Prisma.ProductTranslationWhereInput[]
  productId?: Prisma.StringFilter<"ProductTranslation"> | string
  localeCode?: Prisma.StringFilter<"ProductTranslation"> | string
  title?: Prisma.StringFilter<"ProductTranslation"> | string
  price?: Prisma.StringNullableFilter<"ProductTranslation"> | string | null
  description?: Prisma.StringNullableFilter<"ProductTranslation"> | string | null
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}, "productId_localeCode">

export type ProductTranslationOrderByWithAggregationInput = {
  productId?: Prisma.SortOrder
  localeCode?: Prisma.SortOrder
  title?: Prisma.SortOrder
  price?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ProductTranslationCountOrderByAggregateInput
  _max?: Prisma.ProductTranslationMaxOrderByAggregateInput
  _min?: Prisma.ProductTranslationMinOrderByAggregateInput
}

export type ProductTranslationScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProductTranslationScalarWhereWithAggregatesInput | Prisma.ProductTranslationScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProductTranslationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProductTranslationScalarWhereWithAggregatesInput | Prisma.ProductTranslationScalarWhereWithAggregatesInput[]
  productId?: Prisma.StringWithAggregatesFilter<"ProductTranslation"> | string
  localeCode?: Prisma.StringWithAggregatesFilter<"ProductTranslation"> | string
  title?: Prisma.StringWithAggregatesFilter<"ProductTranslation"> | string
  price?: Prisma.StringNullableWithAggregatesFilter<"ProductTranslation"> | string | null
  description?: Prisma.StringNullableWithAggregatesFilter<"ProductTranslation"> | string | null
}

export type ProductTranslationCreateInput = {
  localeCode: string
  title: string
  price?: string | null
  description?: string | null
  product: Prisma.ProductCreateNestedOneWithoutTranslationsInput
}

export type ProductTranslationUncheckedCreateInput = {
  productId: string
  localeCode: string
  title: string
  price?: string | null
  description?: string | null
}

export type ProductTranslationUpdateInput = {
  localeCode?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  product?: Prisma.ProductUpdateOneRequiredWithoutTranslationsNestedInput
}

export type ProductTranslationUncheckedUpdateInput = {
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  localeCode?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProductTranslationCreateManyInput = {
  productId: string
  localeCode: string
  title: string
  price?: string | null
  description?: string | null
}

export type ProductTranslationUpdateManyMutationInput = {
  localeCode?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProductTranslationUncheckedUpdateManyInput = {
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  localeCode?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProductTranslationListRelationFilter = {
  every?: Prisma.ProductTranslationWhereInput
  some?: Prisma.ProductTranslationWhereInput
  none?: Prisma.ProductTranslationWhereInput
}

export type ProductTranslationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProductTranslationOrderByRelevanceInput = {
  fields: Prisma.ProductTranslationOrderByRelevanceFieldEnum | Prisma.ProductTranslationOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ProductTranslationProductIdLocaleCodeCompoundUniqueInput = {
  productId: string
  localeCode: string
}

export type ProductTranslationCountOrderByAggregateInput = {
  productId?: Prisma.SortOrder
  localeCode?: Prisma.SortOrder
  title?: Prisma.SortOrder
  price?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type ProductTranslationMaxOrderByAggregateInput = {
  productId?: Prisma.SortOrder
  localeCode?: Prisma.SortOrder
  title?: Prisma.SortOrder
  price?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type ProductTranslationMinOrderByAggregateInput = {
  productId?: Prisma.SortOrder
  localeCode?: Prisma.SortOrder
  title?: Prisma.SortOrder
  price?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type ProductTranslationCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.ProductTranslationCreateWithoutProductInput, Prisma.ProductTranslationUncheckedCreateWithoutProductInput> | Prisma.ProductTranslationCreateWithoutProductInput[] | Prisma.ProductTranslationUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.ProductTranslationCreateOrConnectWithoutProductInput | Prisma.ProductTranslationCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.ProductTranslationCreateManyProductInputEnvelope
  connect?: Prisma.ProductTranslationWhereUniqueInput | Prisma.ProductTranslationWhereUniqueInput[]
}

export type ProductTranslationUncheckedCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.ProductTranslationCreateWithoutProductInput, Prisma.ProductTranslationUncheckedCreateWithoutProductInput> | Prisma.ProductTranslationCreateWithoutProductInput[] | Prisma.ProductTranslationUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.ProductTranslationCreateOrConnectWithoutProductInput | Prisma.ProductTranslationCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.ProductTranslationCreateManyProductInputEnvelope
  connect?: Prisma.ProductTranslationWhereUniqueInput | Prisma.ProductTranslationWhereUniqueInput[]
}

export type ProductTranslationUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.ProductTranslationCreateWithoutProductInput, Prisma.ProductTranslationUncheckedCreateWithoutProductInput> | Prisma.ProductTranslationCreateWithoutProductInput[] | Prisma.ProductTranslationUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.ProductTranslationCreateOrConnectWithoutProductInput | Prisma.ProductTranslationCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.ProductTranslationUpsertWithWhereUniqueWithoutProductInput | Prisma.ProductTranslationUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.ProductTranslationCreateManyProductInputEnvelope
  set?: Prisma.ProductTranslationWhereUniqueInput | Prisma.ProductTranslationWhereUniqueInput[]
  disconnect?: Prisma.ProductTranslationWhereUniqueInput | Prisma.ProductTranslationWhereUniqueInput[]
  delete?: Prisma.ProductTranslationWhereUniqueInput | Prisma.ProductTranslationWhereUniqueInput[]
  connect?: Prisma.ProductTranslationWhereUniqueInput | Prisma.ProductTranslationWhereUniqueInput[]
  update?: Prisma.ProductTranslationUpdateWithWhereUniqueWithoutProductInput | Prisma.ProductTranslationUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.ProductTranslationUpdateManyWithWhereWithoutProductInput | Prisma.ProductTranslationUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.ProductTranslationScalarWhereInput | Prisma.ProductTranslationScalarWhereInput[]
}

export type ProductTranslationUncheckedUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.ProductTranslationCreateWithoutProductInput, Prisma.ProductTranslationUncheckedCreateWithoutProductInput> | Prisma.ProductTranslationCreateWithoutProductInput[] | Prisma.ProductTranslationUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.ProductTranslationCreateOrConnectWithoutProductInput | Prisma.ProductTranslationCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.ProductTranslationUpsertWithWhereUniqueWithoutProductInput | Prisma.ProductTranslationUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.ProductTranslationCreateManyProductInputEnvelope
  set?: Prisma.ProductTranslationWhereUniqueInput | Prisma.ProductTranslationWhereUniqueInput[]
  disconnect?: Prisma.ProductTranslationWhereUniqueInput | Prisma.ProductTranslationWhereUniqueInput[]
  delete?: Prisma.ProductTranslationWhereUniqueInput | Prisma.ProductTranslationWhereUniqueInput[]
  connect?: Prisma.ProductTranslationWhereUniqueInput | Prisma.ProductTranslationWhereUniqueInput[]
  update?: Prisma.ProductTranslationUpdateWithWhereUniqueWithoutProductInput | Prisma.ProductTranslationUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.ProductTranslationUpdateManyWithWhereWithoutProductInput | Prisma.ProductTranslationUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.ProductTranslationScalarWhereInput | Prisma.ProductTranslationScalarWhereInput[]
}

export type ProductTranslationCreateWithoutProductInput = {
  localeCode: string
  title: string
  price?: string | null
  description?: string | null
}

export type ProductTranslationUncheckedCreateWithoutProductInput = {
  localeCode: string
  title: string
  price?: string | null
  description?: string | null
}

export type ProductTranslationCreateOrConnectWithoutProductInput = {
  where: Prisma.ProductTranslationWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductTranslationCreateWithoutProductInput, Prisma.ProductTranslationUncheckedCreateWithoutProductInput>
}

export type ProductTranslationCreateManyProductInputEnvelope = {
  data: Prisma.ProductTranslationCreateManyProductInput | Prisma.ProductTranslationCreateManyProductInput[]
  skipDuplicates?: boolean
}

export type ProductTranslationUpsertWithWhereUniqueWithoutProductInput = {
  where: Prisma.ProductTranslationWhereUniqueInput
  update: Prisma.XOR<Prisma.ProductTranslationUpdateWithoutProductInput, Prisma.ProductTranslationUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.ProductTranslationCreateWithoutProductInput, Prisma.ProductTranslationUncheckedCreateWithoutProductInput>
}

export type ProductTranslationUpdateWithWhereUniqueWithoutProductInput = {
  where: Prisma.ProductTranslationWhereUniqueInput
  data: Prisma.XOR<Prisma.ProductTranslationUpdateWithoutProductInput, Prisma.ProductTranslationUncheckedUpdateWithoutProductInput>
}

export type ProductTranslationUpdateManyWithWhereWithoutProductInput = {
  where: Prisma.ProductTranslationScalarWhereInput
  data: Prisma.XOR<Prisma.ProductTranslationUpdateManyMutationInput, Prisma.ProductTranslationUncheckedUpdateManyWithoutProductInput>
}

export type ProductTranslationScalarWhereInput = {
  AND?: Prisma.ProductTranslationScalarWhereInput | Prisma.ProductTranslationScalarWhereInput[]
  OR?: Prisma.ProductTranslationScalarWhereInput[]
  NOT?: Prisma.ProductTranslationScalarWhereInput | Prisma.ProductTranslationScalarWhereInput[]
  productId?: Prisma.StringFilter<"ProductTranslation"> | string
  localeCode?: Prisma.StringFilter<"ProductTranslation"> | string
  title?: Prisma.StringFilter<"ProductTranslation"> | string
  price?: Prisma.StringNullableFilter<"ProductTranslation"> | string | null
  description?: Prisma.StringNullableFilter<"ProductTranslation"> | string | null
}

export type ProductTranslationCreateManyProductInput = {
  localeCode: string
  title: string
  price?: string | null
  description?: string | null
}

export type ProductTranslationUpdateWithoutProductInput = {
  localeCode?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProductTranslationUncheckedUpdateWithoutProductInput = {
  localeCode?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProductTranslationUncheckedUpdateManyWithoutProductInput = {
  localeCode?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type ProductTranslationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  productId?: boolean
  localeCode?: boolean
  title?: boolean
  price?: boolean
  description?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productTranslation"]>



export type ProductTranslationSelectScalar = {
  productId?: boolean
  localeCode?: boolean
  title?: boolean
  price?: boolean
  description?: boolean
}

export type ProductTranslationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"productId" | "localeCode" | "title" | "price" | "description", ExtArgs["result"]["productTranslation"]>
export type ProductTranslationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}

export type $ProductTranslationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProductTranslation"
  objects: {
    product: Prisma.$ProductPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    productId: string
    localeCode: string
    title: string
    price: string | null
    description: string | null
  }, ExtArgs["result"]["productTranslation"]>
  composites: {}
}

export type ProductTranslationGetPayload<S extends boolean | null | undefined | ProductTranslationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProductTranslationPayload, S>

export type ProductTranslationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProductTranslationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProductTranslationCountAggregateInputType | true
  }

export interface ProductTranslationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProductTranslation'], meta: { name: 'ProductTranslation' } }
  /**
   * Find zero or one ProductTranslation that matches the filter.
   * @param {ProductTranslationFindUniqueArgs} args - Arguments to find a ProductTranslation
   * @example
   * // Get one ProductTranslation
   * const productTranslation = await prisma.productTranslation.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProductTranslationFindUniqueArgs>(args: Prisma.SelectSubset<T, ProductTranslationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProductTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProductTranslationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProductTranslation that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProductTranslationFindUniqueOrThrowArgs} args - Arguments to find a ProductTranslation
   * @example
   * // Get one ProductTranslation
   * const productTranslation = await prisma.productTranslation.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProductTranslationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProductTranslationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProductTranslationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProductTranslation that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductTranslationFindFirstArgs} args - Arguments to find a ProductTranslation
   * @example
   * // Get one ProductTranslation
   * const productTranslation = await prisma.productTranslation.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProductTranslationFindFirstArgs>(args?: Prisma.SelectSubset<T, ProductTranslationFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProductTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProductTranslationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProductTranslation that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductTranslationFindFirstOrThrowArgs} args - Arguments to find a ProductTranslation
   * @example
   * // Get one ProductTranslation
   * const productTranslation = await prisma.productTranslation.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProductTranslationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProductTranslationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProductTranslationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProductTranslations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductTranslationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProductTranslations
   * const productTranslations = await prisma.productTranslation.findMany()
   * 
   * // Get first 10 ProductTranslations
   * const productTranslations = await prisma.productTranslation.findMany({ take: 10 })
   * 
   * // Only select the `productId`
   * const productTranslationWithProductIdOnly = await prisma.productTranslation.findMany({ select: { productId: true } })
   * 
   */
  findMany<T extends ProductTranslationFindManyArgs>(args?: Prisma.SelectSubset<T, ProductTranslationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductTranslationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProductTranslation.
   * @param {ProductTranslationCreateArgs} args - Arguments to create a ProductTranslation.
   * @example
   * // Create one ProductTranslation
   * const ProductTranslation = await prisma.productTranslation.create({
   *   data: {
   *     // ... data to create a ProductTranslation
   *   }
   * })
   * 
   */
  create<T extends ProductTranslationCreateArgs>(args: Prisma.SelectSubset<T, ProductTranslationCreateArgs<ExtArgs>>): Prisma.Prisma__ProductTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProductTranslationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProductTranslations.
   * @param {ProductTranslationCreateManyArgs} args - Arguments to create many ProductTranslations.
   * @example
   * // Create many ProductTranslations
   * const productTranslation = await prisma.productTranslation.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProductTranslationCreateManyArgs>(args?: Prisma.SelectSubset<T, ProductTranslationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a ProductTranslation.
   * @param {ProductTranslationDeleteArgs} args - Arguments to delete one ProductTranslation.
   * @example
   * // Delete one ProductTranslation
   * const ProductTranslation = await prisma.productTranslation.delete({
   *   where: {
   *     // ... filter to delete one ProductTranslation
   *   }
   * })
   * 
   */
  delete<T extends ProductTranslationDeleteArgs>(args: Prisma.SelectSubset<T, ProductTranslationDeleteArgs<ExtArgs>>): Prisma.Prisma__ProductTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProductTranslationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProductTranslation.
   * @param {ProductTranslationUpdateArgs} args - Arguments to update one ProductTranslation.
   * @example
   * // Update one ProductTranslation
   * const productTranslation = await prisma.productTranslation.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProductTranslationUpdateArgs>(args: Prisma.SelectSubset<T, ProductTranslationUpdateArgs<ExtArgs>>): Prisma.Prisma__ProductTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProductTranslationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProductTranslations.
   * @param {ProductTranslationDeleteManyArgs} args - Arguments to filter ProductTranslations to delete.
   * @example
   * // Delete a few ProductTranslations
   * const { count } = await prisma.productTranslation.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProductTranslationDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProductTranslationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProductTranslations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductTranslationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProductTranslations
   * const productTranslation = await prisma.productTranslation.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProductTranslationUpdateManyArgs>(args: Prisma.SelectSubset<T, ProductTranslationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one ProductTranslation.
   * @param {ProductTranslationUpsertArgs} args - Arguments to update or create a ProductTranslation.
   * @example
   * // Update or create a ProductTranslation
   * const productTranslation = await prisma.productTranslation.upsert({
   *   create: {
   *     // ... data to create a ProductTranslation
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProductTranslation we want to update
   *   }
   * })
   */
  upsert<T extends ProductTranslationUpsertArgs>(args: Prisma.SelectSubset<T, ProductTranslationUpsertArgs<ExtArgs>>): Prisma.Prisma__ProductTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProductTranslationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProductTranslations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductTranslationCountArgs} args - Arguments to filter ProductTranslations to count.
   * @example
   * // Count the number of ProductTranslations
   * const count = await prisma.productTranslation.count({
   *   where: {
   *     // ... the filter for the ProductTranslations we want to count
   *   }
   * })
  **/
  count<T extends ProductTranslationCountArgs>(
    args?: Prisma.Subset<T, ProductTranslationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProductTranslationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProductTranslation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductTranslationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProductTranslationAggregateArgs>(args: Prisma.Subset<T, ProductTranslationAggregateArgs>): Prisma.PrismaPromise<GetProductTranslationAggregateType<T>>

  /**
   * Group by ProductTranslation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductTranslationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProductTranslationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProductTranslationGroupByArgs['orderBy'] }
      : { orderBy?: ProductTranslationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProductTranslationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProductTranslationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProductTranslation model
 */
readonly fields: ProductTranslationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProductTranslation.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProductTranslationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProductTranslation model
 */
export interface ProductTranslationFieldRefs {
  readonly productId: Prisma.FieldRef<"ProductTranslation", 'String'>
  readonly localeCode: Prisma.FieldRef<"ProductTranslation", 'String'>
  readonly title: Prisma.FieldRef<"ProductTranslation", 'String'>
  readonly price: Prisma.FieldRef<"ProductTranslation", 'String'>
  readonly description: Prisma.FieldRef<"ProductTranslation", 'String'>
}
    

// Custom InputTypes
/**
 * ProductTranslation findUnique
 */
export type ProductTranslationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductTranslation
   */
  select?: Prisma.ProductTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductTranslation
   */
  omit?: Prisma.ProductTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductTranslationInclude<ExtArgs> | null
  /**
   * Filter, which ProductTranslation to fetch.
   */
  where: Prisma.ProductTranslationWhereUniqueInput
}

/**
 * ProductTranslation findUniqueOrThrow
 */
export type ProductTranslationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductTranslation
   */
  select?: Prisma.ProductTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductTranslation
   */
  omit?: Prisma.ProductTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductTranslationInclude<ExtArgs> | null
  /**
   * Filter, which ProductTranslation to fetch.
   */
  where: Prisma.ProductTranslationWhereUniqueInput
}

/**
 * ProductTranslation findFirst
 */
export type ProductTranslationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductTranslation
   */
  select?: Prisma.ProductTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductTranslation
   */
  omit?: Prisma.ProductTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductTranslationInclude<ExtArgs> | null
  /**
   * Filter, which ProductTranslation to fetch.
   */
  where?: Prisma.ProductTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductTranslations to fetch.
   */
  orderBy?: Prisma.ProductTranslationOrderByWithRelationInput | Prisma.ProductTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProductTranslations.
   */
  cursor?: Prisma.ProductTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductTranslations.
   */
  distinct?: Prisma.ProductTranslationScalarFieldEnum | Prisma.ProductTranslationScalarFieldEnum[]
}

/**
 * ProductTranslation findFirstOrThrow
 */
export type ProductTranslationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductTranslation
   */
  select?: Prisma.ProductTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductTranslation
   */
  omit?: Prisma.ProductTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductTranslationInclude<ExtArgs> | null
  /**
   * Filter, which ProductTranslation to fetch.
   */
  where?: Prisma.ProductTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductTranslations to fetch.
   */
  orderBy?: Prisma.ProductTranslationOrderByWithRelationInput | Prisma.ProductTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProductTranslations.
   */
  cursor?: Prisma.ProductTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductTranslations.
   */
  distinct?: Prisma.ProductTranslationScalarFieldEnum | Prisma.ProductTranslationScalarFieldEnum[]
}

/**
 * ProductTranslation findMany
 */
export type ProductTranslationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductTranslation
   */
  select?: Prisma.ProductTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductTranslation
   */
  omit?: Prisma.ProductTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductTranslationInclude<ExtArgs> | null
  /**
   * Filter, which ProductTranslations to fetch.
   */
  where?: Prisma.ProductTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductTranslations to fetch.
   */
  orderBy?: Prisma.ProductTranslationOrderByWithRelationInput | Prisma.ProductTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProductTranslations.
   */
  cursor?: Prisma.ProductTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductTranslations.
   */
  skip?: number
  distinct?: Prisma.ProductTranslationScalarFieldEnum | Prisma.ProductTranslationScalarFieldEnum[]
}

/**
 * ProductTranslation create
 */
export type ProductTranslationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductTranslation
   */
  select?: Prisma.ProductTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductTranslation
   */
  omit?: Prisma.ProductTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductTranslationInclude<ExtArgs> | null
  /**
   * The data needed to create a ProductTranslation.
   */
  data: Prisma.XOR<Prisma.ProductTranslationCreateInput, Prisma.ProductTranslationUncheckedCreateInput>
}

/**
 * ProductTranslation createMany
 */
export type ProductTranslationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProductTranslations.
   */
  data: Prisma.ProductTranslationCreateManyInput | Prisma.ProductTranslationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ProductTranslation update
 */
export type ProductTranslationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductTranslation
   */
  select?: Prisma.ProductTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductTranslation
   */
  omit?: Prisma.ProductTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductTranslationInclude<ExtArgs> | null
  /**
   * The data needed to update a ProductTranslation.
   */
  data: Prisma.XOR<Prisma.ProductTranslationUpdateInput, Prisma.ProductTranslationUncheckedUpdateInput>
  /**
   * Choose, which ProductTranslation to update.
   */
  where: Prisma.ProductTranslationWhereUniqueInput
}

/**
 * ProductTranslation updateMany
 */
export type ProductTranslationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProductTranslations.
   */
  data: Prisma.XOR<Prisma.ProductTranslationUpdateManyMutationInput, Prisma.ProductTranslationUncheckedUpdateManyInput>
  /**
   * Filter which ProductTranslations to update
   */
  where?: Prisma.ProductTranslationWhereInput
  /**
   * Limit how many ProductTranslations to update.
   */
  limit?: number
}

/**
 * ProductTranslation upsert
 */
export type ProductTranslationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductTranslation
   */
  select?: Prisma.ProductTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductTranslation
   */
  omit?: Prisma.ProductTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductTranslationInclude<ExtArgs> | null
  /**
   * The filter to search for the ProductTranslation to update in case it exists.
   */
  where: Prisma.ProductTranslationWhereUniqueInput
  /**
   * In case the ProductTranslation found by the `where` argument doesn't exist, create a new ProductTranslation with this data.
   */
  create: Prisma.XOR<Prisma.ProductTranslationCreateInput, Prisma.ProductTranslationUncheckedCreateInput>
  /**
   * In case the ProductTranslation was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProductTranslationUpdateInput, Prisma.ProductTranslationUncheckedUpdateInput>
}

/**
 * ProductTranslation delete
 */
export type ProductTranslationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductTranslation
   */
  select?: Prisma.ProductTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductTranslation
   */
  omit?: Prisma.ProductTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductTranslationInclude<ExtArgs> | null
  /**
   * Filter which ProductTranslation to delete.
   */
  where: Prisma.ProductTranslationWhereUniqueInput
}

/**
 * ProductTranslation deleteMany
 */
export type ProductTranslationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProductTranslations to delete
   */
  where?: Prisma.ProductTranslationWhereInput
  /**
   * Limit how many ProductTranslations to delete.
   */
  limit?: number
}

/**
 * ProductTranslation without action
 */
export type ProductTranslationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductTranslation
   */
  select?: Prisma.ProductTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductTranslation
   */
  omit?: Prisma.ProductTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductTranslationInclude<ExtArgs> | null
}
